# agents/writer.py
# The Writer is the final agent — it combines research + analysis into a polished report.
# Note: this prompt takes THREE inputs: {topic}, {research}, {analysis}

from langchain_anthropic import ChatAnthropic
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

from state import ResearchState

WRITER_PROMPT = """You are a professional business writer.

Write a polished, concise business report in markdown format.

Topic: {topic}

Research Findings:
{research}

SWOT Analysis:
{analysis}

Write the report using this structure:

# Business Report: {topic}

## Executive Summary
[2-3 sentences summarizing the key takeaways]

## Key Research Findings
[4 bullet points, one per research question — keep each to 1-2 sentences]

## SWOT Analysis
[Format the SWOT cleanly with headers and bullets]

## Conclusion
[2-3 sentences with a forward-looking perspective]

---
*Report generated by AI research workflow*

Use professional, clear language. Do not add any extra sections."""


def writer(state: ResearchState) -> dict:
    llm = ChatAnthropic(model="claude-3-5-haiku-20241022")
    prompt = ChatPromptTemplate.from_template(WRITER_PROMPT)
    chain = prompt | llm | StrOutputParser()

    # This agent reads from THREE state fields
    report = chain.invoke(
        {
            "topic": state["topic"],
            "research": state["research"],
            "analysis": state["analysis"],
        }
    )

    return {"report": report}
